# Generated by Django 4.0 on 2021-12-17 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='images/default.png', upload_to='perfiles/')),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_cumpleaños', models.DateField(default=datetime.date.today)),
                ('genero', models.CharField(blank=True, choices=[('hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=40, verbose_name='Gender')),
                ('completo', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user')),
            ],
        ),
    ]
