# Generated by Django 4.0 on 2021-12-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='titulo',
        ),
        migrations.AddField(
            model_name='comment',
            name='favoritos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='ranking',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
