# Generated by Django 4.0 on 2021-12-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_contatecno_upvote_favoritos_downvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='categorias/'),
        ),
    ]
