# Generated by Django 4.0 on 2021-12-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_categoria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='image',
            field=models.ImageField(default='images/defaul.png', upload_to='categorias/'),
        ),
    ]
