# Generated by Django 4.0 on 2021-12-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_categoria_image_alter_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=30),
        ),
    ]
